dbt_snowflake_learning:
  outputs:
    dev:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: DEV_DB
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA_DEV') }}"
      threads: 1
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER')}}"
      warehouse: COMPUTE_WH

    prod:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: PROD_DB
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA_PROD') }}"
      threads: 1
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER')}}"
      warehouse: COMPUTE_WH
  target: dev
