name: dbt CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
  SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
  SNOWFLAKE_SCHEMA_DEV: ${{ secrets.SNOWFLAKE_SCHEMA_DEV }}
  SNOWFLAKE_SCHEMA_PROD: ${{ secrets.SNOWFLAKE_SCHEMA_PROD }}

jobs:
  dbt_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install requirements
        run: pip install -r requirements.txt 

      - name: Install dbt dependencies
        run: cd dbt_snowflake_learning && dbt deps

      - name: Run lint check
        run: cd dbt_snowflake_learning && sqlfluff lint models --dialect snowflake

      - name: Run dbt test
        run: cd dbt_snowflake_learning && dbt test --profiles-dir ./

      - name: dbt run
        run: cd dbt_snowflake_learning && dbt run --profiles-dir ./

      - name: dbt build
        run: cd dbt_snowflake_learning && dbt build --profiles-dir ./ 